apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: sample-java
  name: sample-java
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sample-java
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: sample-java
    spec:
      containers:
      - image: $IMAGE_URL
        name: sample-java
        resources: {}
status: {}
